### ISSUE TITLE
Remove dataclasses dependency?

### ISSUE THREAD

**Issue by PavlosMelissinos** [mrdimosthenis/Synapses#13]
Hey there, congratulations for this really polished project :)

In [the pyproject.toml for your python implementation](https://github.com/mrdimosthenis/Synapses/blob/8e4afce484bc41d6ba3b386048215e1f612e6101/implementation/Python/pyproject.toml) you require the [dataclasses library](https://pypi.org/project/dataclasses/), which is a python 3.6 backport of [the core dataclasses library](https://docs.python.org/3/library/dataclasses.html) that was introduced in python 3.7 a couple years ago.

Have you considered upgrading to python 3.7+ (maybe even 3.8) and removing this dependency?

**Comment by mrdimosthenis** [comment]
Hi @PavlosMelissinos .
Thank you for the issue and your pull request 🙂 .
I didn't upgrade the python version because it is not supported by the pyFunctional library.

**Comment by PavlosMelissinos** [comment]
Ah, fair enough!

The <3.7 constraint in PyFunctional seems to be more bureaucratic than practical and the latest version of the project on github seems to support 3.8 too. If you eventually decide to update you can replace its entry in `pyprojects.toml` to `PyFunctional = { git = "https://github.com/EntilZha/PyFunctional.git", rev = "8c555e5" }
